#!/bin/sh
echo "start..."
basedir='/home/jenkins/workspace/testJob'
echo "$*"
echo "$1"
echo "$@"


case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/scripts/setupssh.js" "$SSH_CREDENTIALID"
  . "/tmp/envVar.sh"
  ret=$?
else 
  node  "$basedir/scripts/setupssh.js" "$SSH_CREDENTIALID"
  . "/tmp/envVar.sh"
  ret=$?
fi
exit $ret