#!/bin/bash -xe
echo "start..."
basedir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
echo $basedir

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/scripts/setupssh.js" "$@"
  . "/tmp/envVar.sh"
  ret=$?
else 
  node  "$basedir/scripts/setupssh.js" "$@"
  . "/tmp/envVar.sh"
  ret=$?
fi
exit $ret