#!/bin/bash -xe
echo "start..."
basedir=$( cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P )
echo $basedir

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/scripts/setupssh.js" "$@"
  . "/tmp/envVar.sh"
  ret=$?
else 
  node  "$basedir/scripts/setupssh.js" "$@"
  . "/tmp/envVar.sh"
  ret=$?
fi
exit $ret